### ISSUE TITLE
Define Table Relations (Feature request)

### ISSUE THREAD

**Issue by louagej** [jerometwell/pynonymizer#56]
**SQL database with redundant data**
We have a database with redundant data.
For example there is a `Customer` table and a `Sales Header` table.
Both tables contain the fields Customer Name, Customer Address, ...

**Anonymization with table relations**
While anonymization is going on, it could be (very) useful to define a table relation like this:

```yaml
tables:
  Customer:
    schema: dbo
    columns:
      Name: first_name
      Address: street_address
  Sales Header:
    schema: dbo
    columns:
      Customer No: [Relation: Customer.No]
      Customer Name: [Customer.Name]
      Address:  [Customer.Address]
```

So after processing the `Customer` table, we could then retrieve the already anonymized data from this table and apply it on the next ones.
The first column with the table relation. The following columns with the anonymized data from the related record.

**Comment by jerometwell** [comment]
I have nothing against this in principle, although i worry about the update complexity implications behind having table dependencies inside configurations. 
presumably this would need to go in a single statement or transaction to avoid the foreign key checks. 

Do you have any thoughts as to how the resulting SQL statement might look / how it would change the existing approach?

Also, as a workaround you might consider a strategy like this (although admittedly I'm not sure how this scales to large tables)
```yml
tables:
  Customer:
    schema: dbo
    columns:
      Name: first_name
      Address: street_address
  Sales Header:
    schema: dbo
    columns:
      Customer Name: 
        type: literal
        value: (SELECT TOP 1 Name FROM [Customer] WHERE [Customer].[No] = [Sales Header].[Customer No])
```

I'd be interested to hear your thoughts here!
