### ISSUE TITLE
Concatenate anonymized fields into one field (User Question)

### ISSUE THREAD

**Issue by louagej** [jerometwell/pynonymizer#57]
Hi,

I have a contact table that holds, `First Name`, `Surname` and `Name`.
The `Name` field is always filled with the `First Name` and `Surname`.
Is it possible to have the anonymized fields of `First Name` and `Surname` concatenated into the field `Name`?

**Already tried**
```yaml
      Name:
        type: literal
        value: (SELECT TOP1 ([First Name] + ' ' + Surname) FROM [Contact] WHERE [Contact].[No_] = [Contact].[No_])
```

**Comment by jerometwell** [comment]
so, the `literal` [column strategy](https://github.com/jerometwell/pynonymizer/blob/master/doc/strategyfiles.md#column-strategy-literal) is literally a replacement for the field subquery in the anonymization update statement, so anything that's valid in your database's syntax can be used here.

**Comment by jerometwell** [comment]
I'm pretty sure the `TOP1` (should be `TOP 1`) is what's causing the sql to be invalid here :)

**Comment by louagej** [comment]
Hi Jerome,

Thank you for pointing the typo. But I'm afraid that's not the solution for my problem.
Let me try to explain it with the screenshot below:

I have a Contact Mr. Andy Teal that I want to anonymize.
When the strategyfile hits the Name field, the field `First Name` and `Surname` aren't commited yet.
```yaml
tables:
  Contact:
    schema: dbo
    columns:
      First Name: first_name
      Surname: last_name
      Middle Name: empty
      Name:
        type: literal
        value: (SELECT [First Name] + ' ' + Surname)
```
PS: I simplified the table name for to visualize the yaml more human readable

the result is that it takes the uncommitted values of these fields.
Below a screenshot of before and after:

![image](https://user-images.githubusercontent.com/7229592/115297909-0a31d300-a15d-11eb-8fda-6cfad64dba5b.png)

So What I should achieve is to have the value `Deborah Middleton` in the Name field.

Regards,
Job

**Comment by jerometwell** [comment]
Thank you for explaining - I can see the difficulty now!

One thing I feel i need to say up front is this kind of row-level consistency wasn't part of pynonymizer's original design concerns. I still think we can support this use case, though. 

Updating it in one go - This seems like a hard problem, even in SQL, without knowledge of the seed table (which pynonymizer only has at runtime). So my brainstorming has two outcomes:

* Pray that there's some kind of self-referential syntax in raw sql (any ideas? 😇)
* Add some kind of self-referencing parameters to the `literal` column strategy:
e.g. `( (SELECT ${First Name} + ' ' + ${Surname}) )`
that pynonymizer would replace with the column's seed table column id (something like `first_name_abcdef1234`)

Another kludge-hack workaround might be run statements in `scripts.after` after the "main" anonymization to update all the calculated/redundant columns, but if you have constraints that might limit your options.

**Comment by louagej** [comment]
Hi Jerome,

This is what I tried so far:

1. Read on Uncommitted Isolation Level
```yaml
      Name:
        type: literal
        value: (SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED BEGIN TRAN (SELECT [First Name] + ' ' + [Surname]) COMMIT TRAN)
```
When this SQL runs, I receive an error the syntax isn't correct. But this should work since it works in a plain .sql file as a query
```console
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]
Incorrect syntax near the keyword 'SET'. (156)
(SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near ')'. (102)")
```
I also tried to enter semicolons in the SQL statement, but I received the same error:
```yaml
      Name:
        type: literal
        value: (SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; BEGIN TRAN; (SELECT [First Name] + ' ' + [Surname]); COMMIT TRAN;)
```
```console
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]
Incorrect syntax near the keyword 'SET'. (156)
(SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near ')'. (102)")
```

2. Add Table Contact twice in strategy file
```yaml
  Contact:
    schema: dbo
    columns:
      First Name: first_name
      Surname: last_name
      Middle Name: empty
  Contact:
    schema: dbo
    columns:
      Name:
        type: literal
        value: (SELECT [First Name] + ' ' + [Surname])
```
> This schema result that only the last Contact table ran, so there is no anonymized value in the Name field

As far as I know, self-referencing parameters doesn't read uncommitted values, so I don't think we'll find a solution in there.

The Script-after isn't an option, because the concatenated value is used all over the database. So I want this value to be correct before I update other tables.

**Comment by jerometwell** [comment]
> But this should work since it works in a plain .sql file as a query

This might work on its own, but in the context of the `literal` strategy, it has to work as a subquery inside an update statement. So transactions and variables are out, I think!

> 2. Add Table Contact twice in strategy file

That yaml syntax is definitely not something I planned for (doesn't that just result in one dictionary?) This might give us an angle, though:
There IS a verbose table syntax, where the table strategies are given as lists(and therefore you can have duplicates), but you'll need to convert the entire file to this. 

```yaml
# List-of-objects verbose syntax    
tables:
 - table_name: Contact
      schema: dbo
      columns:
        First Name: first_name
        Surname: last_name
        Middle Name: empty
 - table_name: Contact
      schema: dbo
      columns:
        Name:
          type: literal
          value: (SELECT [First Name] + ' ' + [Surname])
```
