### ISSUE TITLE
Add compact syntax for `literal` 

### ISSUE THREAD

**Issue by jerometwell** [jerometwell/pynonymizer#59]
The [literal column strategy](https://github.com/jerometwell/pynonymizer/blob/master/doc/strategyfiles.md#column-strategy-literal) is quite useful, and a great way to break out and drop into field-level sql. I'd like to make this even easier to use, by not requiring the verbose syntax. 

It occured to me that since subqueries require brackets around them in most providers anyway (and aren't conflicting with any other \w+ patterns), they'd be a distinct shorthand for literal, i.e:

```yml
tables:
  customer:
    columns:
      name: (SELECT foo FROM bar WHERE x = y)
      modified_on: ( NOW() )
      login: unique_login
```

If There are cases where you might not want the brackets, but I feel that's handled by gracefully falling back into the verbose syntax.
