### ISSUE TITLE
literal statement doesn't allow to add field in where clause

### ISSUE THREAD

**Issue by louagej** [jerometwell/pynonymizer#62]
Hi Jerome,

In another [question on you repo](https://github.com/jerometwell/pynonymizer/issues/56) you mentioned how to define a table relation with a literal type to update a field with an already anonymized field value from another table.

I was happy at first, but didn't check the result quit well.
It seems that this solution always returns the same value from the table instead of taking the field value in the where clause

**Steps to reproduce the behavior:**
1. Add this in your strategy file
```yaml
tables:
  - table_name: Customer
    schema: dbo
    type: update_columns
    columns:
      Name: company
  - table_name: Sales Header
    schema: dbo
    type: update_columns
    columns:
      Sell-to Customer Name:
        type: literal
        value: (SELECT TOP 1 [Customer].Name FROM [Customer], [Sales Header] WHERE [Customer].No_=[Sales Header].[Sell-to Customer No_])
```
2. Run pynonymizer 

**Expected behavior**
The field Sell-to Customer Name Should be filled with the related Name
But this is the result:
![image](https://user-images.githubusercontent.com/7229592/115610224-da173b00-a2e8-11eb-93b7-e101784ed69f.png)

**Other Scenario**
I Changed the value in the strategy file in the hope the statement would use the [Sell-to Customer No_] value in the query when running
```yaml
tables:
...
      Sell-to Customer Name:
        type: literal
        value: (SELECT TOP 1 [Customer].Name FROM [Customer] WHERE [Customer].[No_]=[Sell-to Customer No_])
```

When running pynonymizer with this literal, this is the error in the command line:
```console
pyodbc.Error: ('HY007', '[HY007] [Microsoft][ODBC SQL Server Driver]Associated statement is not prepared (0) (SQLNumResultCols)')
```

Regards,
Job
